version: "3.9"

services:
  sql_database:
    container_name: sql_database
    image: postgres:13.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: orders_parser
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - bot_parser
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d orders_parser" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - ./config/db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"
  nosql_database:
    image: mongo:latest
    container_name: nosql_database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - ./config/db:/data/db
    networks:
      - bot_parser
    logging:
      options:
        max-size: 10m
        max-file: "3"
  bot:
    container_name: bot
    build:
      context: demon/
      dockerfile: Dockerfile
    command: /usr/bin/supervisord
    networks:
      - bot_parser
    env_file:
      - .env.dev
    restart: always
    volumes:
      - ./config/:/home/app/config
    depends_on:
      - sql_database
      - nosql_database
    logging:
      options:
        max-size: 10m
        max-file: "3"

networks:
  bot_parser:
    driver: bridge
