version: "3.9"

services:
  bot:
    container_name: bot
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      - python3 main.py
    env_file:
      - .env.dev
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"


  database:
    container_name: database
    image: postgres:13.3
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - bot_parser
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d telegram_bot_wallet" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - ./config/db:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"

networks:
  bot_parser:
    driver: bridge
